### ISSUE TITLE
v1.4: Installer fails when choosing us-west-2 region

### ISSUE THREAD

**Issue by suryajak** [tmobile/jazz-installer#120]
### Description

v1.4: Installer doesn't seem to work for certain regions

### Steps to Reproduce

1. Follow install steps as suggested (here)[https://github.com/tmobile/jazz-installer/wiki#install
2. Provide AWS Key details from your personal AWS Account
3. Choose region as us-west-2

**Expected behavior:** 
Installer finishes successfully

**Actual behavior:** 
Installer fails with the error below:
```
Pulling the Jenkins docker image....Failed
Traceback (most recent call last):
 File "./run.py", line 33, in <module>
   main()
 File "./run.py", line 24, in main
   scenarios.execute(key, git_branch_name)
 File "/home/centos/jazz-installer/installscripts/wizard/jazz_scenarios.py", line 25, in execute
   OPTIONS[key][1].start(parameter_list)
 File "/home/centos/jazz-installer/installscripts/wizard/scenarios/stack_with_dockerized_gitlab_jenkins.py", line 37, in start
   get_and_add_docker_jenkins_config(JENKINS_DOCKER_PATH)
 File "/home/centos/jazz-installer/installscripts/wizard/jazz_jenkins.py", line 143, in get_and_add_docker_jenkins_config
   with open("docker_jenkins_vars") as f:
IOError: [Errno 2] No such file or directory: 'docker_jenkins_vars'
```

**Reproduces how often:** 
Multiple attempts to install on a new image stopped at the same place.

**Comment by bleggett** [comment]
Is this because `us-west-2` doesn't support required AWS resources, or because of something else?

**Comment by suryajak** [comment]
During installation if user chooses scenario (2) or (3), the installer attempts to download a custom jenkins image hosted in ecr. For downloading that image, the installer has to pass a flag specific to the region where the container is hosted, which wasn't being done. 
The current patch fix will attempt to pass that flag, so that the installer can proceed.


As part of our next release, we want to utilize [Jenkins CE image](https://github.com/jenkinsci/docker) in favor of our own custom image. I believe that is a better approach and also help us avoid issues like this.
