### ISSUE TITLE
Jazz installation issue

### ISSUE THREAD

**Issue by soma2020** [tmobile/jazz-installer#130]
tried installing Jazz on us-west-2a , made several attempts but the installation did not succeed
**Method1:** Installing using existing Jenkins and existing bitbucket, , all the time the installation fails with the below error
"null_resource.configureExistingJenkinsServer (remote-exec): sudo: chef-client: command not found
Error applying plan:

1 error(s) occurred:

* null_resource.configureExistingJenkinsServer: 1 error(s) occurred:"
Infact there is no way to start the installation from this step and the destroy is not cleaning up the aws resources that were created

**Method2:**  tried installing with existing bitbucket and Jenkins container, the jenkin container creates properly but the installation is not proceeding further with the below error
"
* null_resource.configureExistingJenkinsServer: file: open ../sshkeys/dockerkeys/jenkinskey.pem: no such file or directory in:

${file("${lookup(var.jenkinsservermap, "jenkins_ssh_key")}")}^[[0m^[[0m
Fri Mar 16 09:32:26 UTC 2018"
"
as per my observation container creation process the pem file is getting copied to ../sshekys folder and the subsequent steps are checking for pem file availability within sshkeys/dockerkeys/
here is the ls command that shows the details on pem file location

[centos@ip-172-31-31-201 installscripts]$ cd sshkeys
[centos@ip-172-31-31-201 sshkeys]$ ls -l
total 4
drwxrwxr-x. 2 centos centos    6 Mar 16 09:30 dockerkeys
-r--------. 1 centos centos 1675 Mar 16 09:32 jenkinskey.pem
[centos@ip-172-31-31-201 sshkeys]$ cd dockerkeys
[centos@ip-172-31-31-201 dockerkeys]$ ls -l
total 0
[centos@ip-172-31-31-201 dockerkeys]$

is there a solution to complete the setup either going through method1 or method2

**Comment by suryajak** [comment]
With our [v1.5 release](https://github.com/tmobile/jazz-installer/releases/tag/v1.5) the installer has been improved to handle corner cases better. Can you retry with the new release and see if you are still facing any issues?

**Comment by suryajak** [comment]
@soma2020 : Let us know if you were able to retry the installer.

**Comment by suryajak** [comment]
Closing due to no response.
