### ISSUE TITLE
Rename jazz_installer_vars.json to jazz_config.json

### ISSUE THREAD

**Issue by suryajak** [tmobile/jazz-installer#390]
Rename jazz_installer_vars.json to jazz_config.json. `jazz_installer_vars.json` started as an installer vars file and is now primarily used to drive the behaviour of Jazz at runtime. 

This would involve:
1. Renaming the file during install process
2. Updating build packs to load the updated config file (`loadBuildModules` method)
3. Update [admin microservice](https://github.com/tmobile/jazz/tree/master/core/jazz_admin) to reference new file name.

**Comment by devsatishm** [comment]
Moved to DB for persisting Jazz configurations...
